####################################################################
  #### viya-services-start-restore.yml                            ####
  ####################################################################
  #### Author: SAS Institute Inc.                                 ####
  ####################################################################
  #
  # Copyright (c) 2025-2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
  # SPDX-License-Identifier: Apache-2.0
  #
---
  - import_playbook: ../common/handle_hostgroup_hyphens.yml
    tags:
      - always

  - import_playbook: _services-start-prereq.yml
    vars:
      startmt: false
    tags:
      - always

  - name: Minimal Services for Restore
    hosts: localhost
    gather_facts: false
    tasks:
      - name: Load Minimal Services for Restore from vars file
        include_vars:
          file: viya-services-start-restore-vars.yml
        delegate_to: localhost

      - name: "Check if  {{ SAS_CONFIG_ROOT }}/consul.conf exists"
        stat:
            path: "{{ SAS_CONFIG_ROOT }}/consul.conf"
        become: yes
        delegate_to: "{{ groups['consul'] | first }}"
        register: consul_conf_file

      - block:
          - name: "Check if deployment is multi-tenancy enabled"
            shell: |
                source {{ SAS_CONFIG_ROOT }}/consul.conf
                {{ SASHOME }}/bin/sas-bootstrap-config \
                --token-file {{ SAS_CONFIG_ROOT }}/etc/SASSecurityCertificateFramework/tokens/consul/{{ INSTANCE_ID }}/client.token \
                kv read config/application/sas.multi.tenancy.enabled
            environment: "{{ cli_env }}"
            become: yes
            delegate_to: "{{ groups['consul'] | first }}"
            register: sas_multi_tenancy_key

          - block:
              - set_fact:
                    mt_env: "{{ sas_multi_tenancy_key.stdout | bool }}"
            rescue:
              - set_fact:
                    mt_env: false
        when: consul_conf_file.stat.exists

      - block:
          - set_fact:
                mt_env: false
        when: not consul_conf_file.stat.exists

      - name: Minimal Services that must be started for Restore
        debug:
          var: restore_minimal_services
        delegate_to: localhost

      - name: Filter restore_minimal_services based on mt_env
        set_fact:
          filtered_restore_minimal_services: "{{ restore_minimal_services | difference(only_start_in_mt_env) if mt_env else restore_minimal_services }}"
        delegate_to: localhost

      - name: Set restore_minimal_services globally
        set_fact:
          global_restore_minimal_services: "{{ filtered_restore_minimal_services }}"
        delegate_to: localhost

  - name: Determine where SAS services reside and start the services
    hosts: sas_all
    become: yes
    become_user: root
    gather_facts: false
    any_errors_fatal: true
    vars:
      global_restore_minimal_services: "{{ hostvars['localhost']['global_restore_minimal_services'] }}"
    tasks:
      - block:
          - name: Gather service facts
            service_facts:

          - name: Initialize services list
            set_fact:
              filtered_sas_services: []

          - name: Establish List of all SAS Services
            set_fact:
              filtered_sas_services: "{{ (filtered_sas_services + [item.value.name | replace ('.service', '')]) | unique }}"
            loop: "{{ ansible_facts.services | dict2items }}"
            when: item.value.name is defined and item.value.name.startswith('sas-viya-')

          - name: Create Curated List of the Services to Start
            set_fact:
              intersected_services: "{{ filtered_sas_services | intersect(global_restore_minimal_services) }}"

          - name: Display Curated List of Services to Start
            debug:
                msg: "Host {{ inventory_hostname  }} services to start: {{ intersected_services }}"

          - name: Start SAS Services
            service:
              name: "{{ item }}"
              state: started
            with_items: "{{ intersected_services }}"
        when: not ansible_check_mode
